/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CodeSnippetsRouteImport } from './routes/code-snippets'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth/update-password'
import { Route as AuthSignUpSuccessRouteImport } from './routes/auth/sign-up-success'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as AuthedNotesRouteImport } from './routes/_authed/notes'
import { Route as AuthedDiagramsRouteImport } from './routes/_authed/diagrams'
import { Route as AuthedBookmarksRouteImport } from './routes/_authed/bookmarks'
import { Route as ApiAuthConfirmRouteImport } from './routes/api/auth/confirm'
import { Route as AuthedNoteNoteIdRouteImport } from './routes/_authed/note.$noteId'
import { Route as AuthedDiagramDiagramIdRouteImport } from './routes/_authed/diagram.$diagramId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeSnippetsRoute = CodeSnippetsRouteImport.update({
  id: '/code-snippets',
  path: '/code-snippets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/auth/update-password',
  path: '/auth/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpSuccessRoute = AuthSignUpSuccessRouteImport.update({
  id: '/auth/sign-up-success',
  path: '/auth/sign-up-success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedNotesRoute = AuthedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDiagramsRoute = AuthedDiagramsRouteImport.update({
  id: '/diagrams',
  path: '/diagrams',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBookmarksRoute = AuthedBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthConfirmRoute = ApiAuthConfirmRouteImport.update({
  id: '/api/auth/confirm',
  path: '/api/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedNoteNoteIdRoute = AuthedNoteNoteIdRouteImport.update({
  id: '/note/$noteId',
  path: '/note/$noteId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDiagramDiagramIdRoute = AuthedDiagramDiagramIdRouteImport.update({
  id: '/diagram/$diagramId',
  path: '/diagram/$diagramId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/code-snippets': typeof CodeSnippetsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/bookmarks': typeof AuthedBookmarksRoute
  '/diagrams': typeof AuthedDiagramsRoute
  '/notes': typeof AuthedNotesRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/sign-up-success': typeof AuthSignUpSuccessRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/diagram/$diagramId': typeof AuthedDiagramDiagramIdRoute
  '/note/$noteId': typeof AuthedNoteNoteIdRoute
  '/api/auth/confirm': typeof ApiAuthConfirmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/code-snippets': typeof CodeSnippetsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/bookmarks': typeof AuthedBookmarksRoute
  '/diagrams': typeof AuthedDiagramsRoute
  '/notes': typeof AuthedNotesRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/sign-up-success': typeof AuthSignUpSuccessRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/diagram/$diagramId': typeof AuthedDiagramDiagramIdRoute
  '/note/$noteId': typeof AuthedNoteNoteIdRoute
  '/api/auth/confirm': typeof ApiAuthConfirmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/code-snippets': typeof CodeSnippetsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authed/bookmarks': typeof AuthedBookmarksRoute
  '/_authed/diagrams': typeof AuthedDiagramsRoute
  '/_authed/notes': typeof AuthedNotesRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/sign-up-success': typeof AuthSignUpSuccessRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/_authed/diagram/$diagramId': typeof AuthedDiagramDiagramIdRoute
  '/_authed/note/$noteId': typeof AuthedNoteNoteIdRoute
  '/api/auth/confirm': typeof ApiAuthConfirmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/code-snippets'
    | '/privacy'
    | '/terms'
    | '/bookmarks'
    | '/diagrams'
    | '/notes'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/sign-up'
    | '/auth/sign-up-success'
    | '/auth/update-password'
    | '/diagram/$diagramId'
    | '/note/$noteId'
    | '/api/auth/confirm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/code-snippets'
    | '/privacy'
    | '/terms'
    | '/bookmarks'
    | '/diagrams'
    | '/notes'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/sign-up'
    | '/auth/sign-up-success'
    | '/auth/update-password'
    | '/diagram/$diagramId'
    | '/note/$noteId'
    | '/api/auth/confirm'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/code-snippets'
    | '/privacy'
    | '/terms'
    | '/_authed/bookmarks'
    | '/_authed/diagrams'
    | '/_authed/notes'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/sign-up'
    | '/auth/sign-up-success'
    | '/auth/update-password'
    | '/_authed/diagram/$diagramId'
    | '/_authed/note/$noteId'
    | '/api/auth/confirm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  CodeSnippetsRoute: typeof CodeSnippetsRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AuthErrorRoute: typeof AuthErrorRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthSignUpSuccessRoute: typeof AuthSignUpSuccessRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
  ApiAuthConfirmRoute: typeof ApiAuthConfirmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-snippets': {
      id: '/code-snippets'
      path: '/code-snippets'
      fullPath: '/code-snippets'
      preLoaderRoute: typeof CodeSnippetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/update-password': {
      id: '/auth/update-password'
      path: '/auth/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up-success': {
      id: '/auth/sign-up-success'
      path: '/auth/sign-up-success'
      fullPath: '/auth/sign-up-success'
      preLoaderRoute: typeof AuthSignUpSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/notes': {
      id: '/_authed/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthedNotesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/diagrams': {
      id: '/_authed/diagrams'
      path: '/diagrams'
      fullPath: '/diagrams'
      preLoaderRoute: typeof AuthedDiagramsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/bookmarks': {
      id: '/_authed/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof AuthedBookmarksRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/confirm': {
      id: '/api/auth/confirm'
      path: '/api/auth/confirm'
      fullPath: '/api/auth/confirm'
      preLoaderRoute: typeof ApiAuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/note/$noteId': {
      id: '/_authed/note/$noteId'
      path: '/note/$noteId'
      fullPath: '/note/$noteId'
      preLoaderRoute: typeof AuthedNoteNoteIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/diagram/$diagramId': {
      id: '/_authed/diagram/$diagramId'
      path: '/diagram/$diagramId'
      fullPath: '/diagram/$diagramId'
      preLoaderRoute: typeof AuthedDiagramDiagramIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedBookmarksRoute: typeof AuthedBookmarksRoute
  AuthedDiagramsRoute: typeof AuthedDiagramsRoute
  AuthedNotesRoute: typeof AuthedNotesRoute
  AuthedDiagramDiagramIdRoute: typeof AuthedDiagramDiagramIdRoute
  AuthedNoteNoteIdRoute: typeof AuthedNoteNoteIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedBookmarksRoute: AuthedBookmarksRoute,
  AuthedDiagramsRoute: AuthedDiagramsRoute,
  AuthedNotesRoute: AuthedNotesRoute,
  AuthedDiagramDiagramIdRoute: AuthedDiagramDiagramIdRoute,
  AuthedNoteNoteIdRoute: AuthedNoteNoteIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  CodeSnippetsRoute: CodeSnippetsRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AuthErrorRoute: AuthErrorRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthSignUpSuccessRoute: AuthSignUpSuccessRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
  ApiAuthConfirmRoute: ApiAuthConfirmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
